const express = require("express")

const router = express.Router()

const userRoutes = require("../routes/user_routes/user.routes")
const intakeManagementRoutes = require("../routes/intake_management_routes/intake_management.routes")
const renewalManagementRoute = require("../routes/renewal_management_routes/renewel_management.routes")
const contractManagementRoute = require("../routes/contract_management_route/contract_management.route")
const contractTypeRoutes = require("../routes/contract_management_route/contract_type.routes")
const renewalNotificationRoute = require("../routes/renewal_notification_routes/renewal_notification.route")
const emailTemplateRoutes = require("../routes/renewal_notification_routes/email_template.route")
const contractTemplateRoutes = require("../routes/contract_template_routes/contract_template.routes")
const departmentRoutes = require("../routes/department_routes/department.routes")
const approvalRoutes = require("../routes/approval_routes/approval.routes")
const supplierRoutes = require("../routes/supplier_routes/supplier.routes")
const transactionRoutes = require("../routes/transaction_routes/transaction.routes")
const sowConsolidationRoutes = require("../routes/sow_consolidation_routes/sow_consolidation.routes")
const oldPriceRoutes = require("../routes/old_price_routes/old_price.routes")
const complementaryServiceRoutes = require("../routes/complementary_service_routes/complementary_service.routes")
const priceComparisonRoutes = require("../routes/price_comparison_routes/price_comparison.routes")
const multiYearContractRoutes = require("../routes/multi_year_contract_routes/multi_year_contract.routes")
const volumeDiscountRoutes = require("../routes/volume_discount_routes/volume_discount.routes")
const supplierConsolidationRoutes = require("../routes/supplier_consolidation_routes/supplier_consolidation.routes")
const categoryRoutes = require("../routes/category_routes/category.routes")
const spendAnalyticsRoutes = require("../routes/spend_analytics_routes/spend_analytics.routes")
const dashboardRoutes = require("../routes/dashboard_routes/dashboard.routes")
const chatRoutes = require("../routes/chat_routes/chat.routes")
const costSavingRoutes = require("../routes/costSaving_routes/costSaving.routes")
const licenseRoutes = require("../routes/license_routes/license.routes")
const superadminRoutes = require("../routes/superadmin_routes/superadmin.routes")
const notificationRoutes = require("../routes/notification_routes/notification.routes")
const clientLicenseRoutes = require("../routes/license_routes/client_license.routes")
const inventoryRoutes = require("../routes/inventory_routes/inventory.routes")

router.use("/", userRoutes)
router.use("/", dashboardRoutes)
router.use("/", intakeManagementRoutes)
router.use("/", renewalManagementRoute)
router.use("/", contractManagementRoute)
router.use("/", contractTypeRoutes)
router.use("/", contractTemplateRoutes)
router.use("/", renewalNotificationRoute)
router.use("/", emailTemplateRoutes)
router.use("/", departmentRoutes)
router.use("/", approvalRoutes)
router.use("/", supplierRoutes)
router.use("/", transactionRoutes)
router.use("/", volumeDiscountRoutes)
router.use("/", supplierConsolidationRoutes)
router.use("/", sowConsolidationRoutes)
router.use("/", oldPriceRoutes)
router.use("/", complementaryServiceRoutes)
router.use("/", priceComparisonRoutes)
router.use("/", multiYearContractRoutes)
router.use("/", categoryRoutes)
router.use("/", spendAnalyticsRoutes)
router.use("/", costSavingRoutes)
router.use("/", licenseRoutes)
router.use("/", superadminRoutes)
router.use("/", notificationRoutes)
router.use("/", clientLicenseRoutes)
router.use("/", chatRoutes)
router.use("/", inventoryRoutes)
module.exports = router